import type { ScanResult, Finding } from "../types.js";
import { getRuleReference, groupByOwasp } from "../references.js";

interface HtmlOptions {
  lang?: "zh" | "en";
}

const i18n = {
  zh: {
    title: "安全风险报告",
    subtitle: "基于 OWASP/MITRE/CWE 标准的风险扫描结果",
    target: "扫描目标",
    files: "扫描文件",
    lines: "代码行数",
    time: "扫描耗时",
    riskSummary: "风险概览",
    highRisk: "高风险",
    mediumRisk: "中风险",
    lowRisk: "低风险",
    noRisk: "未检测到安全风险",
    noRiskDesc: "本次扫描未发现匹配 OWASP/CWE 标准的安全风险模式。",
    detailedFindings: "详细发现",
    standards: "相关标准",
    research: "相关研究",
    evidence: "代码证据",
    fpSuppressed: "条可能的误报已隐藏",
    poweredBy: "由 AgentShield 生成 — AI Agent 风险扫描器",
    philosophy: "我们是 X 光机，不是医生。我们照出里面有什么，引用权威标准——你来决定它意味着什么。",
    disclaimer: "本报告基于静态代码模式匹配，每条发现均映射到 OWASP/CWE/MITRE 标准。检测结果仅供参考，具体风险判断取决于使用场景和风险容忍度。",
    line: "行",
    confidence: { high: "高置信度", medium: "中置信度", low: "需审查" },
  },
  en: {
    title: "Security Risk Report",
    subtitle: "Risk scan results based on OWASP/MITRE/CWE standards",
    target: "Target",
    files: "Files Scanned",
    lines: "Lines of Code",
    time: "Scan Time",
    riskSummary: "Risk Summary",
    highRisk: "High Risk",
    mediumRisk: "Medium Risk",
    lowRisk: "Low Risk",
    noRisk: "No Security Risks Detected",
    noRiskDesc: "No patterns matching OWASP/CWE standards were found in this scan.",
    detailedFindings: "Detailed Findings",
    standards: "Standards",
    research: "Research",
    evidence: "Evidence",
    fpSuppressed: "possible false positives suppressed",
    poweredBy: "Generated by AgentShield — AI Agent Risk Scanner",
    philosophy: "We are an X-ray machine, not a doctor. We show what patterns exist, cite established standards — you decide what they mean.",
    disclaimer: "This report is based on static code pattern matching. Each finding is mapped to OWASP/CWE/MITRE standards. Results are for reference only — risk assessment depends on your context and risk tolerance.",
    line: "line",
    confidence: { high: "High confidence", medium: "Medium confidence", low: "Needs review" },
  },
};

export function generateHtmlReport(result: ScanResult, opts: HtmlOptions = {}): string {
  const lang = opts.lang || "zh";
  const t = i18n[lang];
  const realFindings = result.findings.filter(f => !f.possibleFalsePositive);
  const fpCount = result.findings.length - realFindings.length;
  const high = realFindings.filter(f => f.severity === "high").length;
  const medium = realFindings.filter(f => f.severity === "medium").length;
  const low = realFindings.filter(f => f.severity === "low").length;
  const owaspGroups = groupByOwasp(realFindings);

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>🛡️ AgentShield — ${t.title}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
.container { max-width: 900px; margin: 0 auto; padding: 24px 16px; }
.header { text-align: center; padding: 40px 0 32px; border-bottom: 1px solid #21262d; }
.header h1 { font-size: 28px; color: #f0f6fc; margin-bottom: 8px; }
.header .subtitle { color: #8b949e; font-size: 14px; }
.meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; padding: 20px 0; border-bottom: 1px solid #21262d; }
.meta-item { background: #161b22; border-radius: 8px; padding: 12px 16px; }
.meta-item .label { font-size: 12px; color: #8b949e; text-transform: uppercase; letter-spacing: 0.5px; }
.meta-item .value { font-size: 18px; color: #f0f6fc; font-weight: 600; margin-top: 2px; }
.summary { display: flex; justify-content: center; gap: 24px; padding: 32px 0; flex-wrap: wrap; }
.summary-card { text-align: center; padding: 20px 32px; border-radius: 12px; min-width: 120px; }
.summary-card.high { background: rgba(248,81,73,0.1); border: 1px solid rgba(248,81,73,0.3); }
.summary-card.medium { background: rgba(210,153,34,0.1); border: 1px solid rgba(210,153,34,0.3); }
.summary-card.low { background: rgba(63,185,80,0.1); border: 1px solid rgba(63,185,80,0.3); }
.summary-card .count { font-size: 36px; font-weight: 700; }
.summary-card.high .count { color: #f85149; }
.summary-card.medium .count { color: #d29922; }
.summary-card.low .count { color: #3fb950; }
.summary-card .text { font-size: 13px; color: #8b949e; margin-top: 4px; }
.section-title { font-size: 20px; color: #f0f6fc; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #21262d; }
.no-risk { text-align: center; padding: 48px 0; }
.no-risk .icon { font-size: 48px; margin-bottom: 12px; }
.no-risk h2 { color: #3fb950; font-size: 22px; margin-bottom: 8px; }
.no-risk p { color: #8b949e; }
.risk-group { margin-bottom: 24px; }
.risk-group-header { display: flex; align-items: center; gap: 12px; padding: 14px 16px; background: #161b22; border-radius: 8px 8px 0 0; border: 1px solid #21262d; cursor: pointer; }
.risk-group-header:hover { background: #1c2128; }
.risk-group-header .icon { font-size: 20px; }
.risk-group-header .name { font-weight: 600; color: #f0f6fc; flex: 1; }
.risk-group-header .badge { font-size: 12px; padding: 2px 10px; border-radius: 10px; font-weight: 500; }
.badge-high { background: rgba(248,81,73,0.2); color: #f85149; }
.badge-medium { background: rgba(210,153,34,0.2); color: #d29922; }
.badge-low { background: rgba(63,185,80,0.2); color: #3fb950; }
.risk-group-body { border: 1px solid #21262d; border-top: 0; border-radius: 0 0 8px 8px; padding: 16px; }
.risk-desc { color: #8b949e; font-size: 13px; margin-bottom: 12px; }
.standards-bar { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 12px; }
.standards-bar a { font-size: 11px; padding: 2px 8px; border-radius: 4px; background: #21262d; color: #58a6ff; text-decoration: none; }
.standards-bar a:hover { background: #30363d; }
.finding { padding: 10px 0; border-top: 1px solid #21262d; }
.finding:first-child { border-top: 0; }
.finding-loc { font-family: 'SF Mono', Consolas, monospace; font-size: 13px; color: #58a6ff; }
.finding-msg { color: #c9d1d9; font-size: 14px; margin-top: 2px; }
.finding-evidence { font-family: 'SF Mono', Consolas, monospace; font-size: 12px; color: #8b949e; background: #0d1117; border-radius: 4px; padding: 6px 10px; margin-top: 6px; overflow-x: auto; white-space: pre; }
.finding-conf { font-size: 11px; color: #8b949e; margin-top: 4px; }
.footer { text-align: center; padding: 32px 0; border-top: 1px solid #21262d; margin-top: 32px; }
.footer .brand { color: #8b949e; font-size: 13px; }
.footer .philosophy { color: #484f58; font-size: 12px; font-style: italic; margin-top: 8px; max-width: 600px; margin-left: auto; margin-right: auto; }
.footer .disclaimer { color: #484f58; font-size: 11px; margin-top: 12px; max-width: 600px; margin-left: auto; margin-right: auto; }
.paper-ref { font-size: 12px; color: #8b949e; margin-top: 4px; }
</style>
</head>
<body>
<div class="container">

<div class="header">
<h1>🛡️ AgentShield ${t.title}</h1>
<div class="subtitle">${t.subtitle}</div>
</div>

<div class="meta">
<div class="meta-item"><div class="label">${t.target}</div><div class="value">${esc(result.target)}</div></div>
<div class="meta-item"><div class="label">${t.files}</div><div class="value">${result.filesScanned}</div></div>
<div class="meta-item"><div class="label">${t.lines}</div><div class="value">${result.linesScanned.toLocaleString()}</div></div>
<div class="meta-item"><div class="label">${t.time}</div><div class="value">${result.duration}ms</div></div>
</div>

${realFindings.length === 0 ? `
<div class="no-risk">
<div class="icon">✅</div>
<h2>${t.noRisk}</h2>
<p>${t.noRiskDesc}</p>
</div>
` : `
<h2 class="section-title">${t.riskSummary}</h2>
<div class="summary">
<div class="summary-card high"><div class="count">${high}</div><div class="text">${t.highRisk}</div></div>
<div class="summary-card medium"><div class="count">${medium}</div><div class="text">${t.mediumRisk}</div></div>
<div class="summary-card low"><div class="count">${low}</div><div class="text">${t.lowRisk}</div></div>
</div>

<h2 class="section-title">${t.detailedFindings}</h2>
${[...owaspGroups.entries()]
  .sort((a, b) => sevRank(a[1]) - sevRank(b[1]))
  .map(([category, findings]) => renderGroup(category, findings as Finding[], t))
  .join("\n")}

${fpCount > 0 ? `<p style="color:#8b949e;font-size:13px;text-align:center;margin-top:16px;">ℹ️ ${fpCount} ${t.fpSuppressed}</p>` : ""}
`}

<div class="footer">
<div class="brand">${t.poweredBy}</div>
<div class="philosophy">"${t.philosophy}"</div>
<div class="disclaimer">${t.disclaimer}</div>
</div>

</div>
</body>
</html>`;
}

function renderGroup(category: string, findings: Finding[], t: typeof i18n.zh): string {
  const ref = getRuleReference(findings[0]!.rule);
  const gHigh = findings.filter(f => f.severity === "high").length;
  const gMed = findings.filter(f => f.severity === "medium").length;
  const gLow = findings.filter(f => f.severity === "low").length;
  const icon = gHigh > 0 ? "🔴" : gMed > 0 ? "🟡" : "🟢";
  const badgeClass = gHigh > 0 ? "badge-high" : gMed > 0 ? "badge-medium" : "badge-low";
  const counts: string[] = [];
  if (gHigh > 0) counts.push(`${gHigh} ${t.highRisk}`);
  if (gMed > 0) counts.push(`${gMed} ${t.mediumRisk}`);
  if (gLow > 0) counts.push(`${gLow} ${t.lowRisk}`);

  const standards: string[] = [];
  if (ref.owasp) standards.push(`<a href="${ref.owasp.url}" target="_blank">OWASP ${ref.owasp.id}</a>`);
  if (ref.cwe) standards.push(`<a href="${ref.cwe.url}" target="_blank">${ref.cwe.id}</a>`);
  if (ref.atlas) standards.push(`<a href="${ref.atlas.url}" target="_blank">ATLAS ${ref.atlas.id}</a>`);

  const papers = ref.papers?.map(p =>
    `<div class="paper-ref">📄 ${esc(p.authors)} (${p.year}) — <em>${esc(p.title)}</em>${p.url ? ` <a href="${p.url}" target="_blank">↗</a>` : ""}</div>`
  ).join("") || "";

  return `<div class="risk-group">
<details open>
<summary class="risk-group-header">
<span class="icon">${icon}</span>
<span class="name">${esc(category)}</span>
<span class="badge ${badgeClass}">${counts.join(" · ")}</span>
</summary>
<div class="risk-group-body">
<div class="risk-desc">${esc(ref.riskDescription)}</div>
${standards.length > 0 ? `<div class="standards-bar">${standards.join("")}</div>` : ""}
${papers}
${findings.map(f => renderFinding(f, t)).join("")}
</div>
</details>
</div>`;
}

function renderFinding(f: Finding, t: typeof i18n.zh): string {
  const loc = f.line ? `${esc(f.file)}:${f.line}` : esc(f.file);
  const confLabel = f.confidence === "high" ? t.confidence.high : f.confidence === "low" ? t.confidence.low : t.confidence.medium;
  return `<div class="finding">
<div class="finding-loc">${loc}</div>
<div class="finding-msg">${esc(f.message)}</div>
${f.evidence ? `<div class="finding-evidence">${esc(f.evidence)}</div>` : ""}
<div class="finding-conf">${confLabel}</div>
</div>`;
}

function sevRank(findings: Finding[]): number {
  if (findings.some(f => f.severity === "high")) return 0;
  if (findings.some(f => f.severity === "medium")) return 1;
  return 2;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// ─── Multi-Engine HTML Report ─────────────────────────

